# 'env' defines default values for unset environment variables.  These may be
# overridden by a correspondingly named environment variable, e.g.
# NOTIFY_AUX_PATH, or NOTIFY_TIMEZONE
env:
  aux_path: ./aux/example
  timezone: US/Pacific

scopes:
- https://www.googleapis.com/auth/gmail.send
- https://www.googleapis.com/auth/gmail.readonly

message:
  subject: event-notify

templates:
- name: alert
  args:
  - name_or_flags: "--timestamp"
    kws:
      action: "store_true"
  - name_or_flags: "--message"
    kws:
      required: True
